// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fr.normandieuniv.cemnws.db;

import fr.normandieuniv.cemnws.db.CemnEtu;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CemnEtu_Roo_Configurable {
    
    declare @type: CemnEtu: @Configurable;
    
}
